services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests yet"

script:
  - docker --version # print the version for logging
  - cd udagram-user-api && docker build -t udagram-user-api . && cd .. # change directory to udagram-user-api and build docker image
  - docker tag udagram-user-api amirbahrami67/udagram-user-api:latest # tag udagram-user-api

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push amirbahrami67/udagram-user-api

