apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  labels:
    run: udagram-frontend
spec:
  type: LoadBalancer # this type makes the service external (accessible from outside of the cluster)
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: udagram-frontend